source 'https://cdn.cocoapods.org/'

use_frameworks!
platform :ios, "10.0"

def common
  pod "Alamofire", "~> 5.1"
  pod "RxSwift", "~> 5.1"
  pod "RxCocoa", "~> 5.1"
end

target "RxAlamofire-iOS" do
  common
end

target "RxAlamofire-iOS-Example" do
  common
end

target "RxAlamofire-tvOS" do
  platform :tvos, "10.0"
  common
end

target "RxAlamofire-tvOS-Example" do
  platform :tvos, "10.0"
  common
end

target "RxAlamofire-watchOS" do
  platform :watchos, "3.0"
  common
end

target "RxAlamofire-macOS" do
  platform :osx, "10.12"
  common
end
